from PyQt5 import *
def lang_rus(self):
	# главная надпись
	self.ui.label.setGeometry(QtCore.QRect(100, 0, 261, 61))
	self.ui.label.setText("КОНВЕРТЕР ВАЛЮТ")
	# place holder
	self.ui.input_price.setPlaceholderText('У меня есть:')
	self.ui.output_amount.setPlaceholderText('Я получу:')	
	# кнопка конверт
	self.ui.pushButton.setText("КОНВЕРТИРУЙ")
	# светлый режим
	self.ui.radio1.setText("светлая тема")
	# тёмный режим
	self.ui.radio2.setText("тёмная тема")
	# режим для слабовидящих
	self.ui.radio3.setText("режим для слабовидящих")
	# first box 
	self.ui.first_box.setItemText(0,"доллар США")
	self.ui.first_box.setItemText(1,"японская иена")
	self.ui.first_box.setItemText(2,"болгарский лев")
	self.ui.first_box.setItemText(3,"кипрский фунт")
	self.ui.first_box.setItemText(4,"чешская крона")
	self.ui.first_box.setItemText(5,"датская крона")
	self.ui.first_box.setItemText(6,"эстонская крона")
	self.ui.first_box.setItemText(7,"фунт стерлингов")
	self.ui.first_box.setItemText(8,"венгерский форинт")
	self.ui.first_box.setItemText(9,"мальтийская лира")
	self.ui.first_box.setItemText(10,"польский злотый")
	self.ui.first_box.setItemText(11,"румынский лей")
	self.ui.first_box.setItemText(12,"румынский новый лей")
	self.ui.first_box.setItemText(13,"шведская крона")
	self.ui.first_box.setItemText(14,"шведская крона")
	self.ui.first_box.setItemText(15,"словацкая крона")
	self.ui.first_box.setItemText(16,"швейцарский франк")
	self.ui.first_box.setItemText(17,"исландская крона")
	self.ui.first_box.setItemText(18,"норвежская крона")
	self.ui.first_box.setItemText(19,"хорватская куна")
	self.ui.first_box.setItemText(20,"турецкая старая лира")
	self.ui.first_box.setItemText(21,"турецкая лира")
	self.ui.first_box.setItemText(22,"австралийский доллар")
	self.ui.first_box.setItemText(23,"бразильский реал")
	self.ui.first_box.setItemText(24,"канадский доллар")
	self.ui.first_box.setItemText(25,"китайский юань")
	self.ui.first_box.setItemText(26,"гонконгский доллар")
	self.ui.first_box.setItemText(27,"индонезийская рупия")
	self.ui.first_box.setItemText(28,"израильский новый шекель")
	self.ui.first_box.setItemText(29,"индийская рупия")
	self.ui.first_box.setItemText(30,"южнокорейская вона")
	self.ui.first_box.setItemText(31,"мексиканское песо")
	self.ui.first_box.setItemText(32,"малайский ринггит")
	self.ui.first_box.setItemText(33,"новозеландский доллар")
	self.ui.first_box.setItemText(34,"филппинское песо")
	self.ui.first_box.setItemText(35,"сингапурский доллар")
	self.ui.first_box.setItemText(36,"тайский бат")
	self.ui.first_box.setItemText(37,"южноафриканский рад")
	self.ui.first_box.setItemText(38,"евро")
	self.ui.first_box.setItemText(39,"российский рубль")
	# second box
	self.ui.second_box.setItemText(0,"доллар США")
	self.ui.second_box.setItemText(1,"японская иена")
	self.ui.second_box.setItemText(2,"болгарский лев")
	self.ui.second_box.setItemText(3,"кипрский фунт")
	self.ui.second_box.setItemText(4,"чешская крона")
	self.ui.second_box.setItemText(5,"датская крона")
	self.ui.second_box.setItemText(6,"эстонская крона")
	self.ui.second_box.setItemText(7,"фунт стерлингов")
	self.ui.second_box.setItemText(8,"венгерский форинт")
	self.ui.second_box.setItemText(9,"мальтийская лира")
	self.ui.second_box.setItemText(10,"польский злотый")
	self.ui.second_box.setItemText(11,"румынский лей")
	self.ui.second_box.setItemText(12,"румынский новый лей")
	self.ui.second_box.setItemText(13,"шведская крона")
	self.ui.second_box.setItemText(14,"шведская крона")
	self.ui.second_box.setItemText(15,"словацкая крона")
	self.ui.second_box.setItemText(16,"швейцарский франк")
	self.ui.second_box.setItemText(17,"исландская крона")
	self.ui.second_box.setItemText(18,"норвежская крона")
	self.ui.second_box.setItemText(19,"хорватская куна")
	self.ui.second_box.setItemText(20,"турецкая старая лира")
	self.ui.second_box.setItemText(21,"турецкая лира")
	self.ui.second_box.setItemText(22,"австралийский доллар")
	self.ui.second_box.setItemText(23,"бразильский реал")
	self.ui.second_box.setItemText(24,"канадский доллар")
	self.ui.second_box.setItemText(25,"китайский юань")
	self.ui.second_box.setItemText(26,"гонконгский доллар")
	self.ui.second_box.setItemText(27,"индонезийская рупия")
	self.ui.second_box.setItemText(28,"израильский новый шекель")
	self.ui.second_box.setItemText(29,"индийская рупия")
	self.ui.second_box.setItemText(30,"южнокорейская вона")
	self.ui.second_box.setItemText(31,"мексиканское песо")
	self.ui.second_box.setItemText(32,"малайский ринггит")
	self.ui.second_box.setItemText(33,"новозеландский доллар")
	self.ui.second_box.setItemText(34,"филппинское песо")
	self.ui.second_box.setItemText(35,"сингапурский доллар")
	self.ui.second_box.setItemText(36,"тайский бат")
	self.ui.second_box.setItemText(37,"южноафриканский рад")
	self.ui.second_box.setItemText(38,"евро")
	self.ui.second_box.setItemText(39,"российский рубль")

def lang_eng(self):
	# главная надпись
	self.ui.label.setText("CURRENCY CONVERTER")
	self.ui.label.setGeometry(QtCore.QRect(100, 0, 300, 61))
	# place holder
	self.ui.input_price.setPlaceholderText('I have:')
	self.ui.output_amount.setPlaceholderText('I will get:')
	# кнопка конверт
	self.ui.pushButton.setText("CONVERT")
	# светлый режим
	self.ui.radio1.setText("white theme")
	# тёмный режим
	self.ui.radio2.setText("dark theme")
	# режим для слабовидящих
	self.ui.radio3.setText("poor vision theme")
	# first box 
	self.ui.first_box.setItemText(0,"US dollar")
	self.ui.first_box.setItemText(1,"Japanese Yen")
	self.ui.first_box.setItemText(2,"Bulgarian Lev")
	self.ui.first_box.setItemText(3,"The Cypherfunks")
	self.ui.first_box.setItemText(4,"Czech Koruna")
	self.ui.first_box.setItemText(5,"Danish Krone")
	self.ui.first_box.setItemText(6,"Estonian kroon")
	self.ui.first_box.setItemText(7,"British Pound")
	self.ui.first_box.setItemText(8,"Hungarian Forint")
	self.ui.first_box.setItemText(9,"Maltese liri")
	self.ui.first_box.setItemText(10,"Polish Zloty")
	self.ui.first_box.setItemText(11,"Romanian Leu") ##################33
	self.ui.first_box.setItemText(12,"Romanian new Leu") ##############3
	self.ui.first_box.setItemText(13,"Swedish Krona")
	self.ui.first_box.setItemText(14,"Swedish Krona") #####################3
	self.ui.first_box.setItemText(15,"Slovic Krona") ##################
	self.ui.first_box.setItemText(16,"Swiss Franc")
	self.ui.first_box.setItemText(17,"Icelandic Krona")
	self.ui.first_box.setItemText(18,"Norwegian Krone")
	self.ui.first_box.setItemText(19,"Croatian Kuna")
	self.ui.first_box.setItemText(20,"Turkish old Lira")
	self.ui.first_box.setItemText(21,"Turkish Lira")
	self.ui.first_box.setItemText(22,"Australian Dollar")
	self.ui.first_box.setItemText(23,"Brazil Real")
	self.ui.first_box.setItemText(24,"Canadian Dollar")
	self.ui.first_box.setItemText(25,"Chinese Yuan")
	self.ui.first_box.setItemText(26,"Hong Kong Dollar")
	self.ui.first_box.setItemText(27,"Indonesian Rupiah")
	self.ui.first_box.setItemText(28,"Israeli Shekel")
	self.ui.first_box.setItemText(29,"Indian Rupee")
	self.ui.first_box.setItemText(30,"Korean Won")
	self.ui.first_box.setItemText(31,"Mexican Peso")
	self.ui.first_box.setItemText(32,"Malaysian Ringgit")
	self.ui.first_box.setItemText(33,"New Zealand Dollar")
	self.ui.first_box.setItemText(34,"Philippine Peso")
	self.ui.first_box.setItemText(35,"Singapore Dollar")
	self.ui.first_box.setItemText(36,"Thai Baht")
	self.ui.first_box.setItemText(37,"South African Rand")
	self.ui.first_box.setItemText(38,"Euro")
	self.ui.first_box.setItemText(39,"Russian Ruble")
	# second box
	self.ui.second_box.setItemText(0,"US dollar")
	self.ui.second_box.setItemText(1,"Japanese Yen")
	self.ui.second_box.setItemText(2,"Bulgarian Lev")
	self.ui.second_box.setItemText(3,"The Cypherfunks")
	self.ui.second_box.setItemText(4,"Czech Koruna")
	self.ui.second_box.setItemText(5,"Danish Krone")
	self.ui.second_box.setItemText(6,"Estonian kroon")
	self.ui.second_box.setItemText(7,"British Pound")
	self.ui.second_box.setItemText(8,"Hungarian Forint")
	self.ui.second_box.setItemText(9,"Maltese liri")
	self.ui.second_box.setItemText(10,"Polish Zloty")
	self.ui.second_box.setItemText(11,"Romanian Leu") ##################33
	self.ui.second_box.setItemText(12,"Romanian new Leu") ##############3
	self.ui.second_box.setItemText(13,"Swedish Krona")
	self.ui.second_box.setItemText(14,"Swedish Krona") #####################3
	self.ui.second_box.setItemText(15,"Slovic Krona") ##################
	self.ui.second_box.setItemText(16,"Swiss Franc")
	self.ui.second_box.setItemText(17,"Icelandic Krona")
	self.ui.second_box.setItemText(18,"Norwegian Krone")
	self.ui.second_box.setItemText(19,"Croatian Kuna")
	self.ui.second_box.setItemText(20,"Turkish old Lira")
	self.ui.second_box.setItemText(21,"Turkish Lira")
	self.ui.second_box.setItemText(22,"Australian Dollar")
	self.ui.second_box.setItemText(23,"Brazil Real")
	self.ui.second_box.setItemText(24,"Canadian Dollar")
	self.ui.second_box.setItemText(25,"Chinese Yuan")
	self.ui.second_box.setItemText(26,"Hong Kong Dollar")
	self.ui.second_box.setItemText(27,"Indonesian Rupiah")
	self.ui.second_box.setItemText(28,"Israeli Shekel")
	self.ui.second_box.setItemText(29,"Indian Rupee")
	self.ui.second_box.setItemText(30,"Korean Won")
	self.ui.second_box.setItemText(31,"Mexican Peso")
	self.ui.second_box.setItemText(32,"Malaysian Ringgit")
	self.ui.second_box.setItemText(33,"New Zealand Dollar")
	self.ui.second_box.setItemText(34,"Philippine Peso")
	self.ui.second_box.setItemText(35,"Singapore Dollar")
	self.ui.second_box.setItemText(36,"Thai Baht")
	self.ui.second_box.setItemText(37,"South African Rand")
	self.ui.second_box.setItemText(38,"Euro")
	self.ui.second_box.setItemText(39,"Russian Ruble")
	