# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        path = os.path.abspath(os.curdir)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 557)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color:#22222e;\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 501, 191))
        self.frame.setStyleSheet("background-color:#fb5b5d;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(100, 0, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(140, 50, 161, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(path + "\\images\\banknotespaymentmoney_billetesdebanco_pag_3773.png"))
        self.label_2.setObjectName("label_2")
################################
        self.radio1 = QtWidgets.QRadioButton(self.frame)
        self.radio1.setGeometry(QtCore.QRect(320, 110, 110, 21))
        self.radio1.setStyleSheet("background-color:white;\n"
"border: 2px solid orange; color:black;\n"
"border-radius: 10;")
        self.radio1.setObjectName("radio1")
################################
        self.radio2 = QtWidgets.QRadioButton(self.frame)
        self.radio2.setGeometry(QtCore.QRect(320, 150, 110, 21))
        self.radio2.setStyleSheet("background-color:white;\n"
"border: 2px solid orange;color:black;\n"
"border-radius: 10;")
        self.radio2.setObjectName("radio2")
#########################
        self.radio3 = QtWidgets.QRadioButton(self.frame)
        self.radio3.setGeometry(QtCore.QRect(320, 70, 160, 21))
        self.radio3.setStyleSheet("background-color:white;\n"
"border: 2px solid orange;color:black;\n"
"border-radius: 10;")
        self.radio3.setObjectName("radio3")
#########################

#########################
        self.output_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.output_amount.setGeometry(QtCore.QRect(40, 410, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.output_amount.setFont(font)
        self.output_amount.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867 ;\n"
"border-radius: 30;\n"
"color:white;")
        self.output_amount.setText("")
        self.output_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.output_amount.setObjectName("output_amount")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 480, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    background-color: #fb5b5d;\n"
"    border-radius: 30;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:#fa4244;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.first_box = QtWidgets.QComboBox(self.centralwidget)
        self.first_box.setGeometry(QtCore.QRect(110, 200, 201, 41))
        self.first_box.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867 ;\n"
"color:white;ZAR")
        self.first_box.setObjectName("first_box")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.first_box.addItem("")
        self.input_price = QtWidgets.QLineEdit(self.centralwidget)
        self.input_price.setGeometry(QtCore.QRect(40, 320, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.input_price.setFont(font)
        self.input_price.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867 ;\n"
"border-radius: 30;\n"
"color:white;")
        self.input_price.setText("")
        self.input_price.setAlignment(QtCore.Qt.AlignCenter)
        self.input_price.setObjectName("input_price")
        self.second_box = QtWidgets.QComboBox(self.centralwidget)
        self.second_box.setGeometry(QtCore.QRect(110, 260, 201, 41))
        self.second_box.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867 ;\n"
"color:white;ZAR")
        self.second_box.setObjectName("second_box")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        self.second_box.addItem("")
        ##############################   button copy
        self.button_copy = QtWidgets.QPushButton(self.centralwidget)
        self.button_copy.setGeometry(QtCore.QRect(430, 480, 60, 60))
        self.button_copy.setStyleSheet("QPushButton {\n"
"    background-color: #fb5b5d;\n"
"    border-radius: 30px;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:#fa4244;\n"
"}")
        self.button_copy.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(path + "\\images\\copy-two-paper-sheets-stroke-symbol-of-interface_icon-icons.com_57868.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_copy.setIcon(icon)
        self.button_copy.setIconSize(QtCore.QSize(40, 40))
        self.button_copy.setObjectName("button_copy")
        ############################### button language
        self.button_lang = QtWidgets.QPushButton(self.centralwidget)
        self.button_lang.setGeometry(QtCore.QRect(430, 400, 60, 60))
        self.button_lang.setStyleSheet("QPushButton {\n"
"    background-color: #fb5b5d;\n"
"    border-radius: 30px;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:#fa4244;\n"
"}")
        self.button_lang.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(path + "\\images\\language.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_lang.setIcon(icon)
        self.button_lang.setIconSize(QtCore.QSize(40, 40))
        self.button_lang.setObjectName("button_lang")
        ###############################
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "КОНВЕРТЕР ВАЛЮТ"))
        self.pushButton.setText(_translate("MainWindow", "КОНВЕРТИРУЙ"))
        self.radio1.setText(_translate("MainWindow", "светлая тема"))
        self.radio2.setText(_translate("MainWindow", "тёмная тема"))
        self.radio3.setText(_translate("MainWindow", "режим для слабовидящих"))
        self.first_box.setItemText(0, _translate("MainWindow", "доллар США"))
        self.first_box.setItemText(1, _translate("MainWindow", "японская иена"))
        self.first_box.setItemText(2, _translate("MainWindow", "болгарский лев"))
        self.first_box.setItemText(3, _translate("MainWindow", "кипрский фунт"))
        self.first_box.setItemText(4, _translate("MainWindow", "чешская крона"))
        self.first_box.setItemText(5, _translate("MainWindow", "датская крона"))
        self.first_box.setItemText(6, _translate("MainWindow", "эстонская крона"))
        self.first_box.setItemText(7, _translate("MainWindow", "фунт стерлингов"))
        self.first_box.setItemText(8, _translate("MainWindow", "венгерский форинт"))
        self.first_box.setItemText(9, _translate("MainWindow", "мальтийская лира"))
        self.first_box.setItemText(10, _translate("MainWindow", "польский злотый"))
        self.first_box.setItemText(11, _translate("MainWindow", "румынский лей"))
        self.first_box.setItemText(12, _translate("MainWindow", "румынский новый лей"))
        self.first_box.setItemText(13, _translate("MainWindow", "шведская крона"))
        self.first_box.setItemText(14, _translate("MainWindow", "шведская крона"))
        self.first_box.setItemText(15, _translate("MainWindow", "словацкая крона"))
        self.first_box.setItemText(16, _translate("MainWindow", "швейцарский франк"))
        self.first_box.setItemText(17, _translate("MainWindow", "исландская крона"))
        self.first_box.setItemText(18, _translate("MainWindow", "норвежская крона"))
        self.first_box.setItemText(19, _translate("MainWindow", "хорватская куна"))
        self.first_box.setItemText(20, _translate("MainWindow", "турецкая старая лира"))
        self.first_box.setItemText(21, _translate("MainWindow", "турецкая лира"))
        self.first_box.setItemText(22, _translate("MainWindow", "австралийский доллар"))
        self.first_box.setItemText(23, _translate("MainWindow", "бразильский реал"))
        self.first_box.setItemText(24, _translate("MainWindow", "канадский доллар"))
        self.first_box.setItemText(25, _translate("MainWindow", "китайский юань"))
        self.first_box.setItemText(26, _translate("MainWindow", "гонконгский доллар"))
        self.first_box.setItemText(27, _translate("MainWindow", "индонезийская рупия"))
        self.first_box.setItemText(28, _translate("MainWindow", "израильский новый шекель"))
        self.first_box.setItemText(29, _translate("MainWindow", "индийская рупия"))
        self.first_box.setItemText(30, _translate("MainWindow", "южнокорейская вона"))
        self.first_box.setItemText(31, _translate("MainWindow", "мексиканское песо"))
        self.first_box.setItemText(32, _translate("MainWindow", "малайский ринггит"))
        self.first_box.setItemText(33, _translate("MainWindow", "новозеландский доллар")) 
        self.first_box.setItemText(34, _translate("MainWindow", "филппинское песо"))
        self.first_box.setItemText(35, _translate("MainWindow", "сингапурский доллар"))
        self.first_box.setItemText(36, _translate("MainWindow", "тайский бат"))
        self.first_box.setItemText(37, _translate("MainWindow", "южноафриканский рад"))
        self.first_box.setItemText(38, _translate("MainWindow", "евро"))
        self.first_box.setItemText(39, _translate("MainWindow", "российский рубль"))
        ############################################################### 
        self.second_box.setItemText(0, _translate("MainWindow", "доллар США"))
        self.second_box.setItemText(1, _translate("MainWindow", "японская иена"))
        self.second_box.setItemText(2, _translate("MainWindow", "болгарский лев"))
        self.second_box.setItemText(3, _translate("MainWindow", "кипрский фунт"))
        self.second_box.setItemText(4, _translate("MainWindow", "чешская крона"))
        self.second_box.setItemText(5, _translate("MainWindow", "датская крона"))
        self.second_box.setItemText(6, _translate("MainWindow", "эстонская крона"))
        self.second_box.setItemText(7, _translate("MainWindow", "фунт стерлингов"))
        self.second_box.setItemText(8, _translate("MainWindow", "венгерский форинт"))
        self.second_box.setItemText(9, _translate("MainWindow", "мальтийская лира"))
        self.second_box.setItemText(10, _translate("MainWindow", "польский злотый"))
        self.second_box.setItemText(11, _translate("MainWindow", "румынский лей"))
        self.second_box.setItemText(12, _translate("MainWindow", "румынский новый лей"))
        self.second_box.setItemText(13, _translate("MainWindow", "шведская крона"))
        self.second_box.setItemText(14, _translate("MainWindow", "шведская крона"))
        self.second_box.setItemText(15, _translate("MainWindow", "словацкая крона"))
        self.second_box.setItemText(16, _translate("MainWindow", "швейцарский франк"))
        self.second_box.setItemText(17, _translate("MainWindow", "исландская крона"))
        self.second_box.setItemText(18, _translate("MainWindow", "норвежская крона"))
        self.second_box.setItemText(19, _translate("MainWindow", "хорватская куна"))
        self.second_box.setItemText(20, _translate("MainWindow", "турецкая старая лира"))
        self.second_box.setItemText(21, _translate("MainWindow", "турецкая лира"))
        self.second_box.setItemText(22, _translate("MainWindow", "австралийский доллар"))
        self.second_box.setItemText(23, _translate("MainWindow", "бразильский реал"))
        self.second_box.setItemText(24, _translate("MainWindow", "канадский доллар"))
        self.second_box.setItemText(25, _translate("MainWindow", "китайский юань"))
        self.second_box.setItemText(26, _translate("MainWindow", "гонконгский доллар"))
        self.second_box.setItemText(27, _translate("MainWindow", "индонезийская рупия"))
        self.second_box.setItemText(28, _translate("MainWindow", "израильский новый шекель"))
        self.second_box.setItemText(29, _translate("MainWindow", "индийская рупия"))
        self.second_box.setItemText(30, _translate("MainWindow", "южнокорейская вона"))
        self.second_box.setItemText(31, _translate("MainWindow", "мексиканское песо"))
        self.second_box.setItemText(32, _translate("MainWindow", "малайский ринггит"))
        self.second_box.setItemText(33, _translate("MainWindow", "новозеландский доллар")) 
        self.second_box.setItemText(34, _translate("MainWindow", "филппинское песо"))
        self.second_box.setItemText(35, _translate("MainWindow", "сингапурский доллар"))
        self.second_box.setItemText(36, _translate("MainWindow", "тайский бат"))
        self.second_box.setItemText(37, _translate("MainWindow", "южноафриканский рад"))
        self.second_box.setItemText(38, _translate("MainWindow", "евро"))
        self.second_box.setItemText(39, _translate("MainWindow", "российский рубль"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
